/**
 * Contact Module Definition & Pipeline Schema
 */
export const CONTACT_MODULE = {
  id: 'contacts',
  name: 'Contacts',
  category: 'Sales & CRM',
  description: 'Enterprise contact management, multi-stage sales pipeline tracking, lead qualification, and representative assignment.',
  actions: ['canView', 'canCreate', 'canEdit', 'canDelete', 'canExport', 'canApprove'],
  defaultPermissions: {
    canView: true,
    canCreate: true,
    canEdit: true,
    canDelete: false,
    canExport: true,
    canApprove: false,
  },
  stages: [
    'Initialization',
    'Qualification',
    'Discovery',
    'Requirement Analysis',
    'Demo / Presentation',
    'Proposal / Quotation',
    'Negotiation',
    'Decision Making',
    'Won',
    'Lost',
  ],
  statuses: [
    'New',
    'Active',
    'Qualified',
    'In Progress',
    'On Hold',
    'Pending',
    'Follow-up Required',
    'Completed',
    'Won',
    'Lost',
    'Cancelled',
  ],
  sources: [
    'Website',
    'Referral',
    'Cold Call',
    'LinkedIn',
    'Social Media',
    'Other',
  ],
  contactTypes: [
    'Individual',
    'Company Representative',
  ],
  categories: [
    'Product',
    'Service',
  ],
  productOptions: [
    'HRMS',
    'IT CRM',
    'Fintech CRM',
    'Cloud ERP',
    'Custom Enterprise Software',
    'AI & ML Assistant',
    'Mobile Apps',
  ],
  serviceOptions: [
    'Cloud Migration & DevOps',
    'Cybersecurity & Compliance',
    'Custom API & Backend Integration',
    'Full-Stack Web Development',
    'Staff Augmentation',
    'UI/UX Design',
  ],
  priorities: [
    'High',
    'Medium',
    'Low',
  ],
  qualificationStatuses: [
    'In Progress',
    'Qualified',
    'Follow-up Required',
    'Disqualified',
  ],
  schema: {
    fields: [
      'id',
      'contactId',
      'uuid',
      'name',
      'email',
      'phone',
      'address',
      'source',
      'customSource',
      'contactType',
      'companyName',
      'designation',
      'profession',
      'annualRevenue',
      'category',
      'productList',
      'serviceList',
      'customProduct',
      'contactMode',
      'customContactMode',
      'meetingType',
      'nextFollowDate',
      'remarks',
      'notes',
      'status',
      'stage',
      'qualificationStatus',
      'qualifiedBy',
      'qualificationDate',
      'priority',
      'assignedTo',
      'assignedToName',
      'assignmentStatus',
      'assignedAt',
      'assignedBy',
      'createdBy',
      'createdAt',
      'updatedAt',
    ],
  },
};

export default CONTACT_MODULE;
